name: Deploy website

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy website
    runs-on: ubuntu-latest
    steps:
      - name: Initialize Node.js environment
        uses: actions/setup-node@v2
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: src
      - name: Check out deploy branch
        uses: actions/checkout@v2
        with:
          ref: deploy
          path: deploy
      - name: Clean up output
        run: git rm -rf *
        working-directory: deploy
      - name: Set up dependencies
        run: npm install
        working-directory: src
      - name: Stylize images
        env:
          STYLIZATION_SDK_API_KEY: ${{ secrets.STYLIZATION_SDK_API_KEY }}
          STYLIZATION_SDK_API_KEY_ID: ${{ secrets.STYLIZATION_SDK_API_KEY_ID }}
          STYLIZATION_SDK_API_ROUTE: ${{ secrets.STYLIZATION_SDK_API_ROUTE }}
          STYLIZATION_SDK_API_URL: ${{ secrets.STYLIZATION_SDK_API_URL }}
        run: npm run stylize
        working-directory: src
      - name: Build website
        run: npm run build -- --output-path=../deploy
        working-directory: src
      - name: Check out website archive
        uses: actions/checkout@v2
        with:
          repository: vinci-conf/website-archive
          path: archive
      - name: Copy archive to output
        run: cp -r archive/* deploy
      - name: Create CNAME
        run: echo "vinci-conf.org" > CNAME
        working-directory: deploy
      - name: Commit result
        run: |
          git config user.email "${{ github.event.pusher.email }}"
          git config user.name "${{ github.event.pusher.name }}"
          git add *
          git diff-index --quiet HEAD || git commit -m "deploy: ${{ github.event.head_commit.message }}"
          git push
        working-directory: deploy
